version: '3.8'

services:
  # OpenTelemetry Collector
  otel-collector:
    image: docker.io/otel/opentelemetry-collector-contrib:0.91.0
    container_name: otel-collector
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml:Z
    ports:
      - "4317:4317"   # OTLP gRPC receiver
      - "4318:4318"   # OTLP HTTP receiver
      - "8888:8888"   # Prometheus metrics exposed by the collector
      - "8889:8889"   # Prometheus exporter metrics
      - "13133:13133" # Health check extension
    depends_on:
      - jaeger
      - prometheus
    networks:
      - otel-network

  # Jaeger for distributed tracing
  jaeger:
    image: docker.io/jaegertracing/all-in-one:1.52
    container_name: jaeger
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - "16686:16686" # Jaeger UI
      - "14250:14250" # gRPC
    networks:
      - otel-network

  # Prometheus for metrics
  prometheus:
    image: docker.io/prom/prometheus:v2.51.1
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:Z
      - prometheus-data:/prometheus:Z
    ports:
      - "9090:9090"   # Prometheus UI
    networks:
      - otel-network

  # Grafana for visualization
  grafana:
    image: docker.io/grafana/grafana:10.2.3
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana-data:/var/lib/grafana:Z
      - ./grafana/provisioning:/etc/grafana/provisioning:Z
    ports:
      - "3000:3000"   # Grafana UI
    depends_on:
      - prometheus
    networks:
      - otel-network

volumes:
  prometheus-data:
  grafana-data:

networks:
  otel-network:
    driver: bridge