global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Scrape OpenTelemetry Collector metrics
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8888']
        labels:
          service: 'otel-collector'

  # Scrape metrics exposed by OpenTelemetry Collector for applications
  - job_name: 'snsupdater-api'
    static_configs:
      - targets: ['otel-collector:8889']
        labels:
          service: 'snsupdater-api'